### PR TITLE
Wording about other collaborative editing platforms

### PR DESCRIPTION
**Pull request by slochower**
I'm not sure whether this fully addresses the concern in #146.

### CODE REVIEW

**Comment by agitter** [comment]
Emphasizing the branches may help readers who do software development and understand what that implies, but we may want to be even more explicit to address #146.  We should keep the phrase about attribution of credit.  The other aspect to highlight would be that Manubot/GitHub closely integrate project management (issues, pull requests, etc.) with content and help orchestrate editing and reviewing large lists of thematically related changes.

**Review by agitter — CHANGES_REQUESTED** [review]
This additional sentence should clarify what we mean.  The text looks good to me.

Can you please update the response to reviewers as well before we merge?

**Comment by slochower** [comment]
Ready for re-review.

**Review by agitter — APPROVED** [review]
Looks good.  In other responses, I often quote the revised text from the updated manuscript.  However, because we're directly linking to the pull request that may be redundant.

**Review by dhimmel — APPROVED** [review]

**Pull request merged**
