### PR TITLE
Track changes using pandiff

### LINKED ISSUE #198: Track changes from initial to revised journal submission
I am guessing we'll need a tracked changes document.

I'd like to give this a try, since it's something we've been trying to improve in https://github.com/manubot/rootstock/issues/54.

### PR DESCRIPTION
**Pull request by dhimmel**
Closes https://github.com/greenelab/meta-review/issues/198

Work in progress.

### CODE REVIEW

**Comment by dhimmel** [comment]
As of https://github.com/greenelab/meta-review/pull/200/commits/cfe911cda72df83ee2f39acbac642c7f9962705b, here's what I've been able to create using [pandiff](https://github.com/davidar/pandiff): [manuscript-diff.pdf](https://github.com/greenelab/meta-review/files/3060467/manuscript-diff.pdf) (printed to PDF from HTML).

In general, it's pretty good. Some limitations / possible pandiff bugs:

+ pandoc-citeproc and pandoc-xnos filters are never executed. Therefore, the citations are in standard ids. This is good to minimize irrelevant diffing (like changed reference numbers), but makes it hard to look up what reference is being cited:

    > image

+ Old/new figures are not shown side-by-side. Currently, just the new figure is shown with no indication of change. It looks like pandiff is not detecting changes to the figure caption (specified as markdown alt text based on Pandoc's `implicit_figures`):

    > image

+ table cells get shifted/munged, likely pandiff bug:

image

So very impressed with pandiff as a potential diffing solution. Still it looks like we have a bit more work to make it production ready. @davidar is pandiff something you're actively maintaining? We are happy to open [issues](https://github.com/davidar/pandiff/issues) for things like the table cell problem if that would be helpful?

**Comment by dhimmel** [comment]
Currently, our pandiff usage is similar to GitHub's [rich diff compare changes](https://github.com/greenelab/meta-review/compare/937c297c6deed1126f4ef7322e3830f406e3df81...output?short_path=aac4f64#diff-aac4f64d59a83008ac3862e7fc0391de) of `manuscript.md` from the `output` branch. However, we potentially can also use pandiff on the output `manuscript.html` documents.

**Comment by slochower** [comment]
> pandoc-citeproc and pandoc-xnos filters are never executed. Therefore, the citations are in standard ids. This is good to minimize irrelevant diffing (like changed reference numbers), but makes it hard to look up what reference is being cited:

Agree, but are you going to show the diff including the new citations? I think reviewers will want to see that. Wouldn't that require passing the diff through `manubot` again?

**Comment by dhimmel** [comment]
In https://github.com/greenelab/meta-review/pull/200/commits/4863e0aeaa64bb854eb23c0e20bb23be17733ac5, I created a standalone HTML output based on the diff of `manuscript.html`. View it [**here**](https://htmlpreview.github.io/?https://github.com/greenelab/meta-review/blob/4863e0aeaa64bb854eb23c0e20bb23be17733ac5/analyses/diff/webpage/manuscript-html-diff.html). This includes diff of rendered reference numbers, but for some reason the references list disappears. Still some issues with the tables.

> Wouldn't that require passing the diff through manubot again?

It is possible we could create a markdown diff using pandiff and then pass through pandoc to render citations.

**Comment by slochower** [comment]
> This includes diff of rendered reference numbers, but for some reason the references list disappears.

Right :) Also agree about the tables. Maybe a quick fix upstream.

**Comment by dhimmel** [comment]
> It is possible we could create a markdown diff using pandiff and then pass through pandoc to render citations.

The issue is that the markdown diff has the citations escaped like:

```
science open, while supporting new massively collaborative models of
{~~research.\~\>research \[\@1DiVJ3t6P\].~~} However, the scientific
community requires tools whose workflows encourage
{~~openness.\~\>openness \[\@IWBJQIkl\].~~} Manuscripts are the
```

**Comment by davidar** [comment]
Thanks for the ping, this looks cool. Yes, if you're able to submit issues with a minimal example reproducing the problem, that would be great. I have some suspicions about what might be going wrong here, but I haven't explicitly tested pandiff against these kinds of cases yet.

**Comment by agitter** [comment]
In addition to this diff, and possibly a manually generated diff I create in Word, should we also link to the source updates?  We could include one of the following in the response letter:
- https://github.com/greenelab/meta-review/compare/v2.0...master
- https://github.com/greenelab/meta-review/compare/v2.0...v3.0

I'm not sure how readable it is because 71 files changed, with more to come.

**Comment by dhimmel** [comment]
The v2 to v3 GitHub diff would be a great addition to response-to-reviewers. It's nice to see all the commits listed like that. Currently GitHub chokes on the rich diff for main-text, but that could be useful if it works in future. I'll add as part of this PR.

**Comment by dhimmel** [comment]
@agitter once we are basing this PR on the the final output, can you create a diff using your Microsoft Word between `plos-comp-bio/diff/old/manuscript.docx` and `plos-comp-bio/diff/new/manuscript.docx`? 

We will then add that file as `plos-comp-bio/diff/diff-from-docx.pdf` (or whatever) to match response to reviewers.

**Comment by agitter** [comment]
@dhimmel I reviewed https://github.com/greenelab/meta-review/tree/5c6a68a721a9866ea2baa7d82ccb0d0e05986acd and didn't find anything else that needs to be changed.  I'm working on the docx diff now.  I'll finish that before reviewing this pull request in full.

Do we want to date stamp this `diff` directory?  I don't anticipate needing another round of revisions for this paper, but it would establish good general practices for Manubot journal submission that others can adopt.

**Comment by dhimmel** [comment]
> Do we want to date stamp this diff directory? I don't anticipate needing another round of revisions for this paper, but it would establish good general practices for Manubot journal submission that others can adopt.

I changed the directory to `diff-v3.0` to match the upcoming release. I think that may actually be better than a date since I think it implies the diff since the previous release.

Sort of related: we should go back to our existing releases and add a couple more notes like, "this release corresponds to the initial PLOS Comp Bio submission"

**Comment by agitter** [comment]
> I changed the directory to diff-v3.0 to match the upcoming release.

Good idea

> we should go back to our existing releases and add a couple more notes

That makes sense to me now that we're doing it in retrospect.  For other manuscripts that I tag, I generally avoid the overhead of updating each release with the journal(s) that it was sent to in case of desk rejections.

I pushed 628f71c with the Word docx diff.  It looks pretty good except for all the broken svgs.  I'm going to the Word diff another way as well.

**Comment by dhimmel** [comment]
>  It looks pretty good except for all the broken svgs.

Also okay to manually edit that diff to delete the broken SVG placeholders.

**Comment by agitter** [comment]
In d5acec0 I manually made docx files by copying the HTML into Word.  I primarily tried this to see whether it is still necessary or if pandoc doxc works as well.  I'll review both Word diffs side-by-side now.

**Comment by agitter** [comment]
Here are the differences I noticed in the Pandoc docx relative to the manual docx:
- Need to manually delete broken svg images
- Table diff looks better
- `Manubot features` section written entirely as a header
- Figure 3 is sized correctly

Both worked well.  I prefer the Pandoc version so I'll remove the broken images and regenerate the PDF.  I'll remove the manual files.

**Comment by agitter** [comment]
@dhimmel `diff-from-docx.pdf` now looks good to me.  However, I noticed that it doesn't include the changes from #216.  Can you please update the new version of these files and I'll make the diff again?

**Comment by dhimmel** [comment]
> However, I noticed that it doesn't include the changes

Ah shoot, my bad. I guess I didn't rerun the download commands. Fixed in https://github.com/greenelab/meta-review/pull/200/commits/50995b53c0759fff43c4db0888ed1cbea9332aa2

**Comment by dhimmel** [comment]
Okay @agitter squash merge this whenever you're ready to.

**Review by agitter — APPROVED** [review]

**Comment by davidar** [comment]
@dhimmel I've just released a new version of pandiff which should fix the problems you noticed, if you'd like to try it again?

**Pull request merged**
