### PR TITLE
Update rootstock on 2018-10-08

### PR DESCRIPTION
**Pull request by dhimmel**
Merge in rootstock commits up to https://github.com/greenelab/manubot-rootstock/commit/830cdc088dee2a61452bd56d990e0277daa0a9af.

Will be useful to help test https://github.com/greenelab/manubot-rootstock/pull/135#issuecomment-427945022 in the wild.

### CODE REVIEW

**Comment by dhimmel** [comment]
Error in the references appears to have [surfaced](https://travis-ci.org/greenelab/meta-review/builds/438793223#L747). Seems that pandoc-citeproc cannot handle `references.json`:

```
Error reading bibliography ./output/references.json Error in $[32].issued: Could not parse RefDate
Error running filter pandoc-citeproc:
Filter returned error status 1
```

Will investigate locally. Found the offending reference:

```json
  {
    "publisher": "Authorea, Inc.",
    "DOI": "10.22541/au.149693987.70506124",
    "type": "dataset",
    "source": "Crossref",
    "title": "The arXiv of the future will not look like the arXiv",
    "author": [
      {
        "given": "Alberto",
        "family": "Pepe"
      },
      {
        "given": "Matteo",
        "family": "Cantiello"
      },
      {
        "given": "Josh",
        "family": "Nicholson"
      }
    ],
    "container-title": "Authorea",
    "issued": {
      "date-parts": [
        []
      ]
    },
    "URL": "https://doi.org/gdqbz3",
    "id": "WDvu1SAV"
  },
```

Note the empty `date-parts`: `'issued': {'date-parts': [[]]}`. I think we used to manually remove this case. I guess the JSON schema let's this pass (or at least our pruning logic does). https://twitter.com/dhimmel/status/1049389960531390470

Can replicate failure with:

```
manubot cite --render doi:10.22541/au.149693987.70506124
```

**Comment by agitter** [comment]
We want to reopen and merge this after updating the manubot version, right?

**Comment by dhimmel** [comment]
> We want to reopen and merge this after updating the manubot version, right?

Yeah I should update rootstock soon. I'll probably just create a new PR rather than reopen this one.

**Comment by dhimmel** [comment]
> We want to reopen and merge this after updating the manubot version, right?

Ah I see it got closed by https://github.com/greenelab/manubot/commit/1508f5afa496cb7237460710b944265accc3b332, which is not what I actually wanted to happen. But this is fine since we can open a new PR.

**Pull request closed without merging**
