### PR TITLE
Rephrase PPPR sentences

### PR DESCRIPTION
**Pull request by dhimmel**
Follows up on https://github.com/greenelab/meta-review/pull/52#discussion_r195462826

Tagging @agitter

### CODE REVIEW

**Comment by dhimmel** [comment]
There should be a good PPPR citation that fits here as well

Here is an okay one https://doi.org/10.12688/f1000research.7968.1. Will look for better

**Review by agitter — APPROVED** [review]

**Comment by agitter** [comment]
@dhimmel I'm looking for PPPR references and believe I have a good one.  http://doi.org/10.1629/uksg.245 includes a section on challenges and the line
> Due to the large workloads scientists have, there is little motivation for them to participate in PPPR, particularly if their contributions to a paper are not acknowledged by the authors and acted upon.

**Comment by agitter** [comment]
I may also add a more general PPPR reference like:
- https://doi.org/10.1016%2Fj.tig.2015.03.006
- https://doi.org/10.1371%2Fjournal.pmed.1001772
- https://doi.org/10.3389/fncom.2012.00063

**Comment by dhimmel** [comment]
@agitter I liked all your references, check out how I integrated them. Is citing all 4 excessive?

**Comment by agitter** [comment]
That's exactly what I was thinking for the reference placement.  4 may be excessive, but it is easy to cut 1-2 later if we want to.

**Pull request merged**
