### PR TITLE
Switch citations to PLOS Comp Bio style

### LINKED ISSUE #233: Reference format
> Your references need to be formatted according to the PLOS style. PLOS uses the numbered citation (citation-sequence) method and first six authors, et al. Authors should be listed as "Last name, First Initial". If using EndNote, please use the following style file: https://endnote.com/style_download/plos-public-library-of-science-all-journals/

See https://editor.citationstyles.org/styleInfo/?styleId=http%3A%2F%2Fwww.zotero.org%2Fstyles%2Fplos-computational-biology

### PR DESCRIPTION
**Pull request by dhimmel**
Closes https://github.com/greenelab/meta-review/issues/233

Note from the PLOS Comp Bio editorial desk as per https://github.com/greenelab/meta-review/issues/226:

> Your references need to be formatted according to the PLOS style. PLOS uses the numbered citation (citation-sequence) method and first six authors, et al. Authors should be listed as "Last name, First Initial". If using EndNote, please use the following style file: https://endnote.com/style_download/plos-public-library-of-science-all-journals/

I don't think we should permanently keep this change, but instead just generate the proper citations and then revert to the Manubot style.

### CODE REVIEW

**Comment by dhimmel** [comment]
As of https://github.com/greenelab/meta-review/pull/228/commits/84d00c76047928d4ca424e60e3ce49cf132d3918, I generated the following PDF locally: [manuscript.pdf](https://github.com/greenelab/meta-review/files/3242822/manuscript.pdf). Overall not bad but some issues with bioRxiv preprints getting interpreted as websites. We could edit the CSL JSON to make them all journal articles and set the journal as _bioRxiv_.

**Comment by dhimmel** [comment]
I am thinking we could take one final pass at updating the frozen metadata following this PRs merger. Should be ready for review now (rebased).

**Comment by agitter** [comment]
Was the frozen metadata generated before adding the reference in #227?

**Comment by dhimmel** [comment]
> Was the frozen metadata generated before adding the reference in #227?

No. Regenerated in https://github.com/greenelab/meta-review/pull/228/commits/18b20013a416d209b38512fb482761a84ed8b7c3

**Comment by dhimmel** [comment]
@agitter I am going to merge this, so I can start working on cleaning up bibliographic metadata. Any further suggestions will be done in a subsequent PR.

**Pull request merged**
