### PR TITLE
Review 3 subscript and workflow caption clarifications

### LINKED ISSUE #116: footnote placement in rendered manuscript should be left-adjusted
in the PDF I have in front of me, the footnotes at end of sentences are not left-flush with the period. this is a minor nit but a nit nonetheless :). is this just a stylesheet issue or ...?

### LINKED ISSUE #119: "it is reviewed by a maintainer and a participant"
are these separate people or the same person? one presumes maintainers are participants, but not vice versa. either way, please clarify! :)

### PR DESCRIPTION
**Pull request by agitter**
Closes #116
Closes #119 

The figure caption change will create a conflict with #180, which I can resolve after we merge #180.

I'm not sure what the best formatting is for the table subscripts in #116.  As far as I know, we don't directly support footnotes.  It would be too hard to find them if we place footnotes at the end of an HTML document.  Placing them in the table caption is confusing because they were not separated by line breaks.  I attempted an ordered list to add the line breaks, but this formatting is still not quite what I wanted.

Any suggestions?  Should we switch to a more complex HTML-based formatting for this caption?

### CODE REVIEW

**Review by dhimmel — APPROVED** [review]

**Comment by agitter** [comment]
@dhimmel the list did not render as a list in the Table caption

image

This is not exactly what I had intended for the new formatting, but it is still better than what we had before.  Do you think we need to find a way to add newlines after each numbered footnote?

**Comment by dhimmel** [comment]
I don't think a numbered list within the caption is a great idea. It would be nice if it worked everywhere, but I think there is a high chance at least one place (like the journal) will not support it.

What about doing "1—Additional functionality" or "1) Additional functionality"

**Comment by agitter** [comment]
I like 1) Additional functionality".  I'll make that edit when I updated the table for #147.

**Comment by agitter** [comment]
I updated the caption in 6e2d476 in #188.

**Pull request merged**
